### ISSUE TITLE
AnymailRequestsAPIError: Invalid JSON in Mailjet API response
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sending a message to 2kapua3@gmail.com from Theta Tau Chapter Management Tool <cmt@thetatau.org>
Mailjet API respons

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#549]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/353/](https://rollbar.com/frank.ventura/CMT/items/353/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/users/views.py", line 453, in form_valid
    form.save()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 309, in save
    self.send_mail(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 259, in send_mail
    email_message.send()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base.py", line 94, in send_messages
    sent = self._send(message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 58, in _send
    return super()._send(message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base.py", line 127, in _send
    recipient_status = self.parse_recipient_status(response, payload, message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/mailjet.py", line 36, in parse_recipient_status
    parsed_response = self.deserialize_json_response(response, payload, message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 103, in deserialize_json_response
    raise AnymailRequestsAPIError("Invalid JSON in %s API response" % self.esp_name,
AnymailRequestsAPIError: Invalid JSON in Mailjet API response
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sending a message to 2kapua3@gmail.com from Theta Tau Chapter Management Tool <cmt@thetatau.org>
Mailjet API response 400 (At least FromEmail or Sender must be provided): ''Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 101, in deserialize_json_response
    return response.json()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by VenturaFranklin** [comment]
Fixed by e1eaeb7d72e1c306be0bee94ca12add01e3aab36
