### ISSUE TITLE
AnymailRequestsAPIError: Invalid JSON in Mailjet API response
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sending a message to zamora.alexander.ssh@gmail.com from Theta Tau Chapter Management Tool <cmt@thetatau.org>
Mailje

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#553]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/359/](https://rollbar.com/frank.ventura/CMT/items/359/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/views.py", line 146, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/views.py", line 74, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/views.py", line 102, in post
    response = self.form_valid(form)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/views.py", line 159, in form_valid
    return form.login(self.request, redirect_url=success_url)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/forms.py", line 195, in login
    ret = perform_login(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/utils.py", line 175, in perform_login
    send_email_confirmation(request, user, signup=signup, email=email)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/utils.py", line 346, in send_email_confirmation
    email_address.send_confirmation(request, signup=signup)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/models.py", line 62, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/models.py", line 169, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/adapter.py", line 464, in send_confirmation_mail
    self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/allauth/account/adapter.py", line 136, in send_mail
    msg.send()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base.py", line 94, in send_messages
    sent = self._send(message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 58, in _send
    return super()._send(message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base.py", line 127, in _send
    recipient_status = self.parse_recipient_status(response, payload, message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/mailjet.py", line 36, in parse_recipient_status
    parsed_response = self.deserialize_json_response(response, payload, message)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 103, in deserialize_json_response
    raise AnymailRequestsAPIError("Invalid JSON in %s API response" % self.esp_name,
AnymailRequestsAPIError: Invalid JSON in Mailjet API response
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Sending a message to zamora.alexander.ssh@gmail.com from Theta Tau Chapter Management Tool <cmt@thetatau.org>
Mailjet API response 400 (At least FromEmail or Sender must be provided): ''Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/anymail/backends/base_requests.py", line 101, in deserialize_json_response
    return response.json()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by VenturaFranklin** [comment]
Fixed by e1eaeb7d72e1c306be0bee94ca12add01e3aab36
