### ISSUE TITLE
Multiple Active Status Issues

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#554]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/360/](https://rollbar.com/frank.ventura/CMT/items/360/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 97, in dispatch
    return super(LoginRequiredMixin, self).dispatch(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 346, in dispatch
    return super(GroupRequiredMixin, self).dispatch(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/forms/views.py", line 409, in post
    or not formset.is_valid()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/formsets.py", line 301, in is_valid
    self.errors
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/formsets.py", line 281, in errors
    self.full_clean()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/formsets.py", line 329, in full_clean
    form_errors = form.errors
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/forms.py", line 381, in full_clean
    self._clean_fields()
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/forms.py", line 399, in _clean_fields
    value = field.clean(value)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/fields.py", line 148, in clean
    value = self.to_python(value)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/forms/models.py", line 1248, in to_python
    value = self.queryset.get(**{key: value})
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/db/models/query.py", line 410, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one User -- it returned 2!
```

**Comment by VenturaFranklin** [comment]
This is happening when a user has multiple active statuses, we need to prevent that
