### ISSUE TITLE
ProgrammingError: column events_event.raised does not exist
LINE 1: ...", "events_event"."host", "events_event"."miles", "events_ev...
                                                             ^


### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#587]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/374/](https://rollbar.com/frank.ventura/CMT/items/374/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/template/defaulttags.py", line 308, in render
    if match:
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/core/paginator.py", line 150, in __len__
    return len(self.object_list)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django_tables2/rows.py", line 325, in __len__
    length = len(self.data)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
ProgrammingError: column events_event.raised does not exist
LINE 1: ...", "events_event"."host", "events_event"."miles", "events_ev...
                                                             ^
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/testCMT/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UndefinedColumn: column events_event.raised does not exist
LINE 1: ...", "events_event"."host", "events_event"."miles", "events_ev...
                                                             ^

```

**Comment by neznour** [comment]
I have the same problem!! did you fix it?

**Comment by VenturaFranklin** [comment]
@neznour yes this happens when you haven't applied a migration.
See https://docs.djangoproject.com/en/4.0/topics/migrations/ and then https://docs.djangoproject.com/en/4.0/topics/migrations/#adding-migrations-to-apps

**Comment by neznour** [comment]
It says no migrations to apply
