### ISSUE TITLE
AssertionError: Expected parent FilterSet 'users.filters.UserRoleListFilter' to have a '.filter_chapter()' method.

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#707]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/429/](https://rollbar.com/frank.ventura/CMT/items/429/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 97, in dispatch
    return super(LoginRequiredMixin, self).dispatch(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 346, in dispatch
    return super(GroupRequiredMixin, self).dispatch(
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/regions/views.py", line 36, in get
    context = self.get_context_data(object=kwargs["slug"])
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/regions/views.py", line 97, in get_context_data
    [x[0] for x in self.filter.qs.values_list("email").distinct()]
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django_filters/filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django_filters/filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django_filters/filters.py", line 779, in __call__
    return self.method(qs, self.f.field_name, value)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django_filters/filters.py", line 800, in method
    assert callable(method), \
AssertionError: Expected parent FilterSet 'users.filters.UserRoleListFilter' to have a '.filter_chapter()' method.
```

**Comment by VenturaFranklin** [comment]
Closed by 5be5e1f35c57227b84605f4c0e03fd19bb9fd014
