### ISSUE TITLE
AttributeError: 'BylawsCreateView' object has no attribute 'object'

### ISSUE THREAD

**Issue by VenturaFranklin** [ThetaTau/CMT#784]
View details in Rollbar: [https://rollbar.com/frank.ventura/CMT/items/476/](https://rollbar.com/frank.ventura/CMT/items/476/)

```
Traceback (most recent call last):
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 105, in dispatch
    return self.handle_no_permission(request)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 77, in handle_no_permission
    return self.no_permissions_fail(request)
  File "/home/Venturafranklin/.virtualenvs/thetatauCMT/lib/python3.9/site-packages/braces/views/_access.py", line 88, in no_permissions_fail
    self.get_login_url(),
  File "/home/Venturafranklin/thetatauCMT/./core/views.py", line 84, in get_login_url
    return self.get_success_url()
  File "/home/Venturafranklin/thetatauCMT/thetatauCMT/forms/views.py", line 2994, in get_success_url
    chapter = self.object.chapter
AttributeError: 'BylawsCreateView' object has no attribute 'object'
```

**Comment by VenturaFranklin** [comment]
Closed by 13e404492e80d0b74c3d2d7d015beec0ef678824
